### PR TITLE
Make FakerRepeatabilityIntegrationTest running in same thread

### PR DESCRIPTION
**Pull request by snuyanzin**

### CODE REVIEW

**Comment by kingthorin** [comment]
Is this instead of the other PR or in addition?

**Comment by snuyanzin** [comment]
addition to fix repeatability

**Comment by bodiam** [comment]
I don't see a reason for this. This code worked fine before `d9c2cc262d29deb3552c9f49ab71edf0b3f6dc30`.

**Comment by snuyanzin** [comment]
how do you that exactly d9c2cc262d29deb3552c9f49ab71edf0b3f6dc30 is the reason?
after that there were about 10 more commits to main branch and no such issue

**Comment by bodiam** [comment]
So, that's interesting: if we enabled the `springApps()` method in Azure, things started failing.

**Comment by bodiam** [comment]
> i wonder if it's because of `springApps()` or just because of any 1 more method which means that if we still have enabled `springApps()` however remove any another method will it work?

I don't think it's because of `springApps` per se, it's not doing much, but I think it's related to this:

```
private static final Random SHARED_RANDOM = new Random()
```

I've done a few random tests, and the funny things is:

```
    public String springApps() {
        String hex = faker.random().hex(4, false); // works
        return "sa-" + hex;
    }
```

This consistently works.

```
    public String springApps() {
        String hex = faker.random().hex(8, false); // works
        return "sa-" + hex;
    }
```

but this:

```
    public String springApps() {
        String hex = faker.random().hex(9, false); // 9 fails. Anything above fails. 8 = 1 byte, 9 = 2 bytes?
        return "sa-" + hex;
    }
```

**Comment by bodiam** [comment]
> well I still suggest to make repeatabale tests in same thread.

Okay, that's fine!

**Pull request merged**
