### PR TITLE
extract duplicate methods "toJavaNames" to a single place

### PR DESCRIPTION
**Pull request by asolntsev**

### CODE REVIEW

**Review by kingthorin — COMMENTED** [review]
Could you change the method names in the tests to proper Java camelCase instead of using underscores?

**Comment by asolntsev** [comment]
> Could you change the method names in the tests to proper Java camelCase instead of using underscores?

Done.

P.S. In fact, **camelCaseIsNotReallyGoodForDescribingTestCases**.
In many project, `we_often_use_underscored_in_test_names`. They are much better readable.

**Review by kingthorin — APPROVED** [review]
Assuming the tests pass or failure is unrelated I'm good with this.

Thanks for the contribution!

**Comment by kingthorin** [comment]
Failure seems unrelated:
```
2024-08-23T19:38:52.9884050Z ##[error]Exception in thread "Thread-13" java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "net.datafaker.internal.helper.CopyOnWriteMap.getOrDefault(Object, Object)" is null
2024-08-23T19:38:52.9892720Z 	at net.datafaker.service.FakeValuesService.fetchObject(FakeValuesService.java:267)
2024-08-23T19:38:52.9893280Z 	at net.datafaker.service.FakeValuesService.safeFetch(FakeValuesService.java:206)
2024-08-23T19:38:52.9895030Z 	at net.datafaker.service.FakeValuesService.resolve(FakeValuesService.java:505)
2024-08-23T19:38:52.9895350Z 	at net.datafaker.service.FakeValuesService.resolve(FakeValuesService.java:492)
2024-08-23T19:38:52.9895870Z 	at net.datafaker.providers.base.AbstractProvider.resolve(AbstractProvider.java:20)
2024-08-23T19:38:52.9896140Z 	at net.datafaker.providers.base.Address.stateAbbr(Address.java:98)
2024-08-23T19:38:52.9896380Z 	at net.datafaker.Issue759Test.fakeSomeData(Issue759Test.java:32)
2024-08-23T19:38:52.9896840Z 	at net.datafaker.Issue759Test$WorkerThread.run(Issue759Test.java:25)
```

**Comment by asolntsev** [comment]
> Failure seems unrelated:

Yes, it's unrelated. It's the same flaky test that I described in https://github.com/datafaker-net/datafaker/pull/1310

**Pull request merged**
