### PR TITLE
Added locations.

### PR DESCRIPTION
**Pull request by bodiam**
I took them from here: https://improwiki.com/en/wiki/improv/list_of_places

### CODE REVIEW

**Review by kingthorin — COMMENTED** [review]
Do you want suggestions for additions or prefer those via another PR?

**Comment by erikpragt-connectid** [comment]
If you want to add items to it, feel free.

**Comment by bodiam** [comment]
I merged it for now cause I need it for a project I'm working on, but feel free to add more data to it!

**Comment by kingthorin** [comment]
Okay, will plan to in the next few days.

**Pull request merged**
