### PR TITLE
Add medical professions in Medical faker

### PR DESCRIPTION
**Pull request by panilya**

### CODE REVIEW

**Review by kingthorin — COMMENTED** [review]
Any source info for this list?

**Comment by panilya** [comment]
Just googled "medical professions". But I'm gonna add more medical professions from this Wikipedia list: https://en.wikipedia.org/wiki/List_of_healthcare_occupations

**Comment by panilya** [comment]
Source: https://en.wikipedia.org/wiki/List_of_healthcare_occupations

**Review by kingthorin — APPROVED** [review]
Thanks

**Pull request merged**
