### PR TITLE
Make pastDateExpression test more stable

### PR DESCRIPTION
**Pull request by snuyanzin**

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by bodiam** [comment]
You triggered a new build?

Seems the code isn't completely repeatable:

```
  ["name.nameWithMiddle"="Gavin Durgan Bauch Jr."]
but the following map entries had different values:
  ["name.nameWithMiddle"="Gavin Durgan Bauch and Sons" (expected: "Gavin Durgan Bauch Jr.")]
```

**Comment by snuyanzin** [comment]
yes, somehow it appeared today not only for this PR

**Comment by bodiam** [comment]
Well, at least it's nice that it's consistently failing...

**Comment by bodiam** [comment]
Correction: I can reproduce this quite often.

**Comment by snuyanzin** [comment]
looks like the issue is with concurrent tests
https://github.com/datafaker-net/datafaker/pull/837 should improve it

**Comment by bodiam** [comment]
I just went through the git history, and git `d9c2cc262d29deb3552c9f49ab71edf0b3f6dc30` caused it.

**Pull request merged**
