### PR TITLE
Add battlefield1 feature. Related issue at https://github.com/DiUS/java-faker/issues/711

### PR DESCRIPTION
**Pull request by coolestjj**
This is the feature update from [This Issue](https://github.com/DiUS/java-faker/issues/711). Please remind me if there is anything wrong in the commit. @bodiam

### CODE REVIEW

**Comment by bodiam** [comment]
Oops, missed this PR (see comments in Javafaker). I'll have a look a bit later, but looks great to me.

**Comment by coolestjj** [comment]
@bodiam I have fixed some problems. Maybe it would pass this time. Thanks for your patience.

**Comment by coolestjj** [comment]
@bodiam Please check the PR. Hopefully you can merge it, thanks

**Comment by bodiam** [comment]
Hi  @coolestjj , I just had another look, and I'm happy to merge it if the spaces are gone in the yml file. For example, the weapon list looks like this :

" SMG 08/18 (TSAR) "

There's an extra space on either end. Please remove them so it looks like:

"SMG 08/18 (TSAR)"

Thanks!

**Comment by coolestjj** [comment]
@bodiam Problem fixed.

**Comment by snuyanzin** [comment]
Hi @coolestjj 
it looks like there is a similar issue with `" A7V "`
could you please also fix it?

**Comment by coolestjj** [comment]
@snuyanzin Sure

**Comment by snuyanzin** [comment]
it looks this test will fail
```java
    @Test
    public void map() {
        assertThat(faker.battlefield1().map()).matches("[A-Za-z0-9,\\- .()']+");
    }
```
As in yaml among other values there is `Łupków Pass` which does not match the expression

**Comment by coolestjj** [comment]
@snuyanzin How is it now?

**Comment by snuyanzin** [comment]
Much better, thank you
there is one more neat comment: in `src/test/java/net/datafaker/Battlefield1Test.java`
could you please remove unused imports?

**Comment by coolestjj** [comment]
@snuyanzin Redundant import removed. And I noticed that the test run failed minutes ago, I wonder why

**Comment by snuyanzin** [comment]
thank you
>  And I noticed that the test run failed minutes ago, I wonder why
looks it does not relate to classes changed/added within this PR

**Comment by Uncle-Road** [comment]
@snuyanzin hello , i see the error information and find the OscarMovieTest with some bug in their test
it match pattern not correct in some case.

**Comment by snuyanzin** [comment]
yes, probably should be fixed with https://github.com/datafaker-net/datafaker/pull/137

**Comment by snuyanzin** [comment]
Merged as https://github.com/datafaker-net/datafaker/commit/61a556e95683e3193dc133dee36ce32a41049014
Thanks for your contribution @coolestjj

**Pull request closed without merging**
