### PR TITLE
Release of 2.0.1 documentation.

### PR DESCRIPTION
**Pull request by bodiam**

### CODE REVIEW

**Comment by kingthorin** [comment]
Restarted CI.

Not sure the 2.0.0 updates are correct?

**Comment by kingthorin** [comment]
CI passed this time.

**Comment by bodiam** [comment]
Thanks @kingthorin ! I'm not sure what happened, my change was just documentation.

**Comment by kingthorin** [comment]
Are the additions to the 2.0.0 notes in this PR correct?

**Pull request merged**
