### PR TITLE
Use spotless to enforce format of en yaml files

### PR DESCRIPTION
**Pull request by kingthorin**
- pom.xml 
    - Update spotless plugin to 2.36.0 
    - Add configuration for spotless to apply to en yaml files 
    - I couldn't get other locales to behave nicely, they might have to be manually re-formatted initially. I'll investigate further for a future PR.
    - Can be applied via `spotless:apply`
- en/*.yml > Reformatted using the new config.

This ensures consistency in quote usage and indents.

### CODE REVIEW

**Comment by bodiam** [comment]
Nice work. I had a quick look, but would it be possible to remove those `\` linebreaks? I'm not really a fan of that.

**Comment by kingthorin** [comment]
I’ll see what I can do.

**Comment by kingthorin** [comment]
Some notes for myself 😀 

For `  <yamlFeatures>` should be able to set `SPLIT_LINES` to `false`
https://www.javadoc.io/doc/com.fasterxml.jackson.dataformat/jackson-dataformat-yaml/latest/com/fasterxml/jackson/dataformat/yaml/YAMLGenerator.Feature.html#SPLIT_LINES

`back_to_the_future.yml` seems to be one of the "first" files alphabetically that this will impact.

**Comment by kingthorin** [comment]
Hopefully that addresses your request.

**Comment by kingthorin** [comment]
Ping @bodiam :grinning:

**Comment by kingthorin** [comment]
I know I can merge my own stuff, and this is now conflicting. Could someone else at least give me a comment here? 🙂

(Yes I’ll fix the conflict, just wondering if there’s other stuff I should also be tackling.)

**Comment by bodiam** [comment]
Ah, sorry! I'm fine with it, go ahead!!

**Comment by kingthorin** [comment]
Thanks, I’ll get it tiddied up tomorrow 😄

**Comment by kingthorin** [comment]
Conflict addressed, and new files formatted.

**Comment by bodiam** [comment]
Nice one, thanks!

**Pull request merged**
