### PR TITLE
feat: Add Tire faker

### PR DESCRIPTION
**Pull request by kingthorin**
- BaseProviders > Add Tire provider.
- EnFile.java > Include tire.yml.
- Tire > New provider.
- tire.yml > New data file for the tire provider (source: https://www.wheel-size.com/tire/ )
- TireTest > Unit tests for the new provider.

Fixes datafaker-net/datafaker#862

### CODE REVIEW

**Comment by kingthorin** [comment]
@snuyanzin @bodiam I think I've missed something simple here but I can't see it, please help.

**Comment by kingthorin** [comment]
Ready for review.

**Comment by bodiam** [comment]
@jaapcoomans any feedback on this?

**Comment by bodiam** [comment]
Thanks @kingthorin for adding this one! I merged it.

**Comment by kingthorin** [comment]
Thanks. Happy to tweak or adjust if/when we get feedback.

**Comment by jaapcoomans** [comment]
@bodiam I was on holiday and had some personal circumstances that prevented me from replying earlier.
@kingthorin Thanks for picking this up! Will try it out soon!

**Pull request merged**
