### PR TITLE
fix/pokemon_fr_localization

### PR DESCRIPTION
**Pull request by TGITS**
Working on some code example for a blog post about Datafaker (in French and not yet publisehd), I have noticed the French localization for the pokemon provider does not seem to work properly.
It seems there was a small typo in the `fr.yaml` resource file (and as a matter of fact the same problem in the `fr-CA.yaml` file for which I have provided the same fix).
I have not found specific unit tests for localization and I have not written some new ones. However I have tested the fixed version against the aformentioned code examples (https://github.com/TGITS/devtoolbox/tree/feat/datafaker/java/library/datafaker/datafaker-example).
Do not hesitate to tell me if you want explicit unit tests to validate the correction.

### CODE REVIEW

**Comment by bodiam** [comment]
Hi @TGITS , tests are always nice, but at the same time I appreciate every contribution and I really don't like to be prescriptive, so if this fixes the issue, all good (I checked, looks good to me)

Also thanks for writing an article about this, that's amazing, I'd love to read it when it's done!

**Comment by TGITS** [comment]
Hi @bodiam,

Thanks for your answer.
The blog post (hopefully the blog posts) will be very basic introductory stuff about Datafaker and will be in French. 
As soon as I will have posted it, I try and send to inform you one way or another.

I was a user of JavaFaker and I now use Datafaker since I've discovered it. Thanks for your work and the library. I find it very useful and I gladly recommend it usage around me.

**Comment by bodiam** [comment]
Thanks for your kind words @TGITS , we're happy you're finding the library useful. If you ever have questions, suggestions, please let us know, and we're happy to help you out!

**Comment by bodiam** [comment]
(PS: not sure if you're aware, but your fix is already published in the 1.7.0-SNAPSHOT version of Datafaker)

**Pull request merged**
