### PR TITLE
Support for email subjects.

### PR DESCRIPTION
**Pull request by bodiam**

### CODE REVIEW

**Comment by kingthorin** [comment]
Needs spotlessapply

**Comment by bodiam** [comment]
> Needs spotlessapply

Doesn't match with default intellij settings. I'll just close the PR

**Comment by kingthorin** [comment]
You can just disable yaml formatting in IntelliJ https://www.jetbrains.com/help/idea/code-style-yaml.html

**Comment by bodiam** [comment]
> You can just disable yaml formatting in IntelliJ https://www.jetbrains.com/help/idea/code-style-yaml.html

I don't see the point of doing that.

**Comment by kingthorin** [comment]
Fair enough. Was just going for a quick workaround.

**Pull request closed without merging**
