### PR TITLE
Add flags to maven to show timestamps during build

### PR DESCRIPTION
**Pull request by snuyanzin**
Could be helpful to see where time is consuming

the result could be seen in build logs at https://github.com/datafaker-net/datafaker/runs/5303678498?check_suite_focus=true#step:4:7

### CODE REVIEW

**Comment by bodiam** [comment]
Just curious, any reason why you needed this?

**Comment by snuyanzin** [comment]
not right now, I picked from another project.
However it could speed up the process to identify the reason if at some certain point build starts consuming more time

**Comment by bodiam** [comment]
Yeah, good idea. I was actually thinking of making the build fail if it ever takes longer than a minute to build. I'm not sure if that's an option with maven though

**Comment by snuyanzin** [comment]
not sure about the whole `mvn` build... At least there are options to fail tests if timeout was reached e.g.
https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#parallelTestsTimeoutForcedInSeconds
and 
https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#parallelTestsTimeoutInSeconds

**Pull request merged**
