### PR TITLE
Added 'addUrl' method

### PR DESCRIPTION
**Pull request by ghost**
fixes https://github.com/datafaker-net/datafaker/issues/714

### CODE REVIEW

**Review by snuyanzin — CHANGES_REQUESTED** [review]
@tcttk thanks for the contribution
1 .Can you please explain how this change relates to custom providers?

2. And as I mentioned in #714 before fixing it please provide a reproducible test case first

**Comment by bodiam** [comment]
Thanks for this PR. Interesting to use a URL for this, how does this work? I expected something like an InputStream or so.

**Comment by snuyanzin** [comment]
@tcttk thanks for the explanation
well I put a code snippet working for the case you've mentioned
> 
```
my-app
|
|----> depends my-datafaker-library (addPath(locale, Paths.get("src/main/resources/de/sample.yml")) does not work ❌)
                           |
                           |----> /resources/sample.yml  
                           |----> depends datafaker-library
```
https://github.com/datafaker-net/datafaker/issues/714#issuecomment-1451568692

it should work.


Regarding changes I'm still a bit skeptic about: there is no any test confirming that it works.
And it means there is no any guarantee that it will keep working while merging other changes

**Comment by snuyanzin** [comment]
ok i see... loading files from other jars looks strange for me...
anyway
>The error I get when I test the case above is
java.lang.IllegalArgumentException: Path should be an existing readable file.

to fix it the condition could be tuned like 
```java
if (path == null || Files.isDirectory(path)) {
            throw new IllegalArgumentException("Path should be an existing file");
        }
```

and no need for a new methods and so on.
the only missing thing still absence of a specific test for  that in tests

**Comment by snuyanzin** [comment]
Can you share the code giving an error?


I tested the code from https://github.com/datafaker-net/datafaker/issues/714#issuecomment-1451568692

and it works ok

**Comment by snuyanzin** [comment]
and what it is the trace in case it is failing?
to be honest it is not reproduced on my machine.... 
that's another point to have a dedicated test for this in repo

**Comment by snuyanzin** [comment]
Thanks for your explanation @tcttk 
Finally I was able to reproduce it...
From one side it's not trivial to create an integration test for this, from another side I made `addPath` working via `addUrl` so most of the time the code is reused and at covered by tests for old `addPath`. 
Please double check if it keeps working for your use case and let us know if you are ok with such changes.

**Pull request merged**
