### PR TITLE
Use RgxGen to cope with StackOverFlow

### LINKED ISSUE #1091: StackOverflowError for regexify
for some of the `regexify` it fails with StackOverflow e.g.

```java
new Faker().regexify("^arn:.+:.+:.*:([0-9]{12}):(.+)$");
```
This is an  issue in generex https://github.com/mifmif/Generex/issues/56
There was a suggestion to use an alternative e.g. https://github.com/curious-odd-man/RgxGen

### PR DESCRIPTION
**Pull request by snuyanzin**
fixes #1091

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by bodiam** [comment]
I don't think we can depend on snapshot versions. If they publish a new version, we would have no idea what kind of code we get into our library. I don't think this would be an acceptable  situation.

**Comment by snuyanzin** [comment]
based on the commit history they are not going to do it...
the latest commit was more than 8 months ago...

**Comment by bodiam** [comment]
I don't really care how often they release, I care that we don't depend on snapshots for production releases. Maybe they change the api in a year, then it would break every Datafaker release depending on the snapshot, including older versions. If they would introduce something malicious, we would download this too automatically. So no, let's not do this.

**Comment by kingthorin** [comment]
Wouldn't that be true of any dependency?

**Review by kingthorin — COMMENTED** [review]
Assuming a release happens and this PR goes forward then I think `src/main/java/module-info.java` will also need updating.

**Comment by snuyanzin** [comment]
it is already a a part of the PR or do you mean something else?

**Comment by kingthorin** [comment]
All good, I totally overlooked it 🤦‍♂️

**Comment by bodiam** [comment]
2.0.0 has been released!

**Comment by snuyanzin** [comment]
thanks for letting know, updated to use released version

**Comment by snuyanzin** [comment]
Merging since now there is no SNAPSHOT version in deps

**Pull request merged**
