### PR TITLE
Generate boolean with probability

### PR DESCRIPTION
**Pull request by NarekDW**
## Add ability to generate boolean value with some predefined probability of true

Example: 
```java
Faker faker = new Faker().withProbabilityConfig(new ProbabilityConfig().withBool(0.0));
boolean falseValue = faker.bool().bool(); // always false

faker = faker.withProbabilityConfig(new ProbabilityConfig().withBool(1.0));
boolean trueValue = faker.bool().bool(); // always true

faker = faker.withProbabilityConfig(new ProbabilityConfig().withBool(0.7));
boolean value = faker.bool().bool(); // will generate true with probability 70 % and false with probability 30 %
```

### CODE REVIEW

**Comment by bodiam** [comment]
Hi @NarekDW . Thanks for this PR, but I'm not really sure about it. This PR is for booleans, but what about numbers? What about ages? What about enums? Or even what about coin flips?

This would require different versions of every method out there, and I'm not sure if that's ideal. What might be better if to change the underlying RandomService instead, and control the behavior through that.

I'm not sure how easy this would be, but it might be a better approach than this. What do you think?

**Comment by NarekDW** [comment]
Hi @bodiam , I'm not sure if I understood you, but do you mean to move this method:
```java
    public boolean bool(double probability) {
        if (probability < 0.0 || probability > 1.0) {
            throw new IllegalArgumentException("Probability parameter should be between [0.0, 1.0]: " + probability);
        }

        return faker.random().nextDouble() < probability;
    }
```
to the `RandomService` (as `nextBoolean(double probability)` method) class, and use it from different classes, right? (including Bool class)

**Comment by bodiam** [comment]
@NarekDWar well, I think we can't change the signature of every method out there just to change the randomness, but I was hoping that maybe by using the RandomService somehow for this, we  wouldnt need to change every method, but the logic could be configured in the Service instead

**Comment by NarekDW** [comment]
Then it could be added to the RandomService class as an additional (overloaded) method, like this:
```java
    public boolean nextBoolean() {
        return random.nextBoolean();
    }

    public boolean nextBoolean(double probability) {
        if (probability < 0.0 || probability > 1.0) {
            throw new IllegalArgumentException("Probability parameter should be between [0.0, 1.0]: " + probability);
        }

        return random.nextDouble() < probability;
    }
```
And used from Bool class, like
```java
    public boolean bool(double probability) {
       return faker.random().nextBoolean(probability);
    }
```

**Comment by snuyanzin** [comment]
Probably to rephrase @bodiam 's idea if i understand it correctly it would make sense to have something like `ProbabilityConfig` which should be taken into account. E.g. 
```java
ProbabilityConfig.with(1, 0.5).with(2, 0.1).with(3, 0.2);
...
```
should mean that in case of numbers it should generate 1 with probability 0.5, 2 with probability 0.1, 3 with probability 0.2 and any other number with probability 0.2.
Similar logic could be applied to other entities

**Comment by NarekDW** [comment]
> Probably to rephrase @bodiam 's idea if i understand it correctly it would make sense to have something like `ProbabilityConfig` which should be taken into account. E.g.
> 
> ```java
> ProbabilityConfig.with(1, 0.5).with(2, 0.1).with(3, 0.2);
> ...
> ```
> 
> should mean that in case of numbers it should generate 1 with probability 0.5, 2 with probability 0.1, 3 with probability 0.2 and any other number with probability 0.2. Similar logic could be applied to other entities

At first glance this looks a bit complicated regarding implementation/integration, but okay, I got the point, will try to implement something like that...

**Comment by NarekDW** [comment]
@bodiam  @snuyanzin I've added a draft version of such a configuration of probabilities, please review the approach.
Also, I'm not sure regarding the API, is it designed convenient or not...
Currently it's possible to configure boolean values distribution only, but it could be enhanced easily for different distribution types for numbers...

**Comment by snuyanzin** [comment]
I didn't get hoe with current implementation it is possible to configure possibilities for 3 numbers like in the example above
```
ProbabilityConfig.with(1, 0.5).with(2, 0.1).with(3, 0.2);
...
```

**Comment by NarekDW** [comment]
@snuyanzin take a look on the last commit (it's a draft example)

**Comment by snuyanzin** [comment]
why should it be separate for bool and int? otherwise next question would be about long, string and etc...
Config should be same for any type. Implementation of generation could be different

**Comment by NarekDW** [comment]
> why should it be separate for bool and int? otherwise next question would be about long, string and etc... Config should be same for any type. Implementation of generation could be different

I'm not sure if I understood the question regarding separation. Do you mean methods `withInt` and `withBool` should be named the same (like `with(...)`) ?

**Comment by snuyanzin** [comment]
mostly about information storage 
```java
 private final double boolProbability;
 private final Map<Integer, Double> intProbability = new HashMap<>();
```

**Comment by NarekDW** [comment]
It's just convenient as for me. 
What could be the alternative?

**Comment by snuyanzin** [comment]
however each new type requires a new map and it will grow endlessly

**Comment by NarekDW** [comment]
By the way, I think probabilities should be configured only in case if we generate some primitive types (Bool, Number, etc).
I can't imagine how it could be used with providers, like Name, Address, Book, Coin and so on...

**Comment by NarekDW** [comment]
> 

Yep, I understand but it is a bit strange to configure probability for objects, like Address, Name, and so on, isn't it?

**Comment by snuyanzin** [comment]
i would consider it from technical point of view.
Everything which is taken from yml configuration or `Option.option` is present as an array. 
So technically speaking we are talking not about name,address or whatever. We are talking only about index which will be random;y defined

**Comment by NarekDW** [comment]
Ok, let me see

**Comment by NarekDW** [comment]
Closing the PR as there are no agreement regarding probability configuration approach.

**Pull request closed without merging**
