### PR TITLE
Faker for Bulgarian street name broken in 1.5.0

### PR DESCRIPTION
**Pull request by eikemeier**
See included regression test

### CODE REVIEW

**Comment by panilya** [comment]
@eikemeier Fixed. Thank you for informing about the problem.

**Comment by snuyanzin** [comment]
I do not think it is fixed...
The issue is more generic
currently it seems the WA is applied only for `bg` while the same is actual for `by`, `ru`, `uk`.

I fear there could be something else (not only address related)
Moreover I would prefer do not change configuration files since they worked for previous releases...

I could have a look at it a bit later or any kind of help is also appreciated

**Comment by bodiam** [comment]
I think (part of) the problem is that FakerIT doesn't run. Running it results in many broken tests. I'm not sure why yet, but I'll have a look.

**Comment by snuyanzin** [comment]
@bodiam probably the fix is relatively simple, I added it to your PR #270

**Comment by snuyanzin** [comment]
it looks it should be fixed within https://github.com/datafaker-net/datafaker/pull/270
I added there a bit more generic test there (for several countries)
@eikemeier could you please double check if your issue is fixed?

**Comment by bodiam** [comment]
@snuyanzin I've reverted the other "fix" in the bg.yml file

**Comment by snuyanzin** [comment]
I guess the issue is fixed (at least it is not reproduced at ci anymore)

**Comment by eikemeier** [comment]
> it looks it should be fixed within #270
> I added there a bit more generic test there (for several countries)
> @eikemeier could you please double check if your issue is fixed?

As far as my test are concerned, the issue is fixed in 1.6.0-SNAPSHOT c02d418a7f1bbbcec0c8b331cba1ce4dca2f7e10

**Pull request closed without merging**
