### PR TITLE
Run AssertJ best practices OpenRewrite recipe

### PR DESCRIPTION
**Pull request by timtebeek**
Consistently use static imports for AssertJ, as a once of code change, [through OpenRewrite](https://docs.openrewrite.org/reference/recipes/java/testing/assertj/assertj).

```
mvn org.openrewrite.maven:rewrite-maven-plugin:4.36.0:run \
  -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-testing-frameworks:1.30.0 \
  -DactiveRecipes=org.openrewrite.java.testing.assertj.Assertj
```

### CODE REVIEW

**Comment by bodiam** [comment]
Thanks for this PR, much appreciated!

**Comment by timtebeek** [comment]
You're welcome; let me know if there's any other types of automated improvements you'd want me to take a look at.
Don't want to overwhelm you with review work if that's not the type of contribution you're looking for right now.

**Comment by bodiam** [comment]
@timtebeeko thanks! There might be a thing, but it could be a tricky one : some of our assertions are pretty useless. They basically test that methods are returning something, and that's about it. Something slightly stricter might be nice. That might be hard to do with static code analysis, but open to suggestions!

**Comment by timtebeek** [comment]
Hmm yes closest thing I could find in OpenRewrite on that so far is [TestsShouldIncludeAssertions](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/java/org/openrewrite/java/testing/cleanup/TestsShouldIncludeAssertions.java), with some test examples in [TestsShouldIncludeAssertionsTest](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/test/kotlin/org/openrewrite/java/testing/cleanup/TestsShouldIncludeAssertionsTest.kt). Not an exact match to what you're looking for, but open to suggestions on how to improve that one or write a new one.

An alternative in that space might be [DiffBlue Cover](https://www.diffblue.com/products/). Fairly new (and pricey), but they have a free trial and might be able to help out for OSS projects. Ideally you'd pinpoint exact area's for improvement through mutation testing and see from there.

**Pull request merged**
