### PR TITLE
Describe provider groups and table with new providers per version

### PR DESCRIPTION
**Pull request by panilya**

### CODE REVIEW

**Comment by panilya** [comment]
Why here's also a commit from another PR? How to prevent it?

**Comment by snuyanzin** [comment]
```
git log --pretty=oneline
```
will show your commits in current branch
If you see these commits locally then it's expected.
First make sure you do not have them locally

**Comment by bodiam** [comment]
> Why here's also a commit from another PR? How to prevent it?

I guess you made a branch of the other PR, instead of main?

**Comment by panilya** [comment]
> > Why here's also a commit from another PR? How to prevent it?
> 
> I guess you made a branch of the other PR, instead of main?

Yes, I `git checkout -b` from previous branch :(

**Pull request closed without merging**
