### PR TITLE
Fix for module-info.

### PR DESCRIPTION
**Pull request by bodiam**

### CODE REVIEW

**Comment by bodiam** [comment]
okay, seems that didn't go well. How do I fix this, anyone?

**Comment by snuyanzin** [comment]
I would suggest to test first what we have after https://github.com/datafaker-net/datafaker/pull/1292

it's very likely it fixes the issue #1281

**Comment by asolntsev** [comment]
@bodiam  I made a "uses ..." commit to fix the issue with ServiceProvider.
But it seems that IdNumberGenerators are still not loaded. I am out of ideas. :(

**Comment by kingthorin** [comment]
For future reference it's better to rebase than merge. When you merge we end up with commits that are already applied to the default branch.

**Comment by kingthorin** [comment]
image

**Comment by asolntsev** [comment]
@kingthorin While we are working on a PR (where every commit can either fix or break something), it's very useful to see all commits separately. I totally don't understand why you can it "mess". 

For me, the mess would be if PR always had only one commit, and you never know what changes this commit contains.

**Comment by kingthorin** [comment]
Don't worry about it. It isn't a blocker.

**Pull request closed without merging**
