### PR TITLE
Fix broken 'Address.streetName' faker for 'bg' locale

### PR DESCRIPTION
**Pull request by panilya**
Issue related to the problem: #252
PR that shows this problem: #250

### CODE REVIEW

**Comment by snuyanzin** [comment]
I wouldn't say that changing a yaml file is a solution. Moreover that configuration worked before...
We need to guarantee that same configuration should continue working if it worked for 1.4.0 and earlier.
Furthermore it looks like the same issue is actual for other locales like by, ru, uk, may be something else not related to address...

**Comment by bodiam** [comment]
Shall we revert https://github.com/datafaker-net/datafaker/commit/702973bffffb4739966a887b83e12cc6b3b23398?

**Comment by panilya** [comment]
> Shall we revert [702973b](https://github.com/datafaker-net/datafaker/commit/702973bffffb4739966a887b83e12cc6b3b23398)?

I think yes. Sorry about that

**Comment by bodiam** [comment]
Don't worry about it, no problem at all!

**Pull request merged**
