### PR TITLE
chore: add support for Azure Spring Apps

### PR DESCRIPTION
**Pull request by bowen5**
Add support for Azure Spring Apps (https://azure.microsoft.com/en-au/products/spring-apps/)

### CODE REVIEW

**Review by snuyanzin — CHANGES_REQUESTED** [review]
Could you please also add a test to
https://github.com/datafaker-net/datafaker/blob/main/src/test/java/net/datafaker/providers/base/AzureTest.java

**Comment by bowen5** [comment]
> Could you please also add a test to https://github.com/datafaker-net/datafaker/blob/main/src/test/java/net/datafaker/providers/base/AzureTest.java

sure thing. added.

**Review by snuyanzin — APPROVED** [review]

**Comment by snuyanzin** [comment]
Thanks for th contribution @bowen5

**Comment by snuyanzin** [comment]
there is no precise calendar
however AFAIK @bodiam is working on a new version (please correct me if I'm wrong)

**Comment by bodiam** [comment]
Well, not actively working on it at this moment, but the idea is to "soon" release 2.x

**Pull request merged**
