### PR TITLE
NameTest testname could be flaky

### PR DESCRIPTION
**Pull request by snuyanzin**
e.g. https://github.com/datafaker-net/datafaker/actions/runs/5554020338/jobs/10143304541#step:5:1027

### CODE REVIEW

**Comment by kingthorin** [comment]
Thanks, I bookmarked that failure to tackle once I got home from vacation 😉

**Comment by snuyanzin** [comment]
sorry =)
next time if you want to the issue you could leave a comment and i will not touch it

**Comment by kingthorin** [comment]
Oh yeah, no big deal. It wasn’t important 😉

**Comment by bodiam** [comment]
I'll release a 2.0.2 version when I get back from my trip.

**Pull request merged**
