### PR TITLE
add philippines first_name and last_name

### PR DESCRIPTION
**Pull request by divinenickname**
Add most popular philippines names

### CODE REVIEW

**Comment by bodiam** [comment]
Salamat! These seem however quite biased towards male names, would it be possible to add a few female names, and maybe even split them like other locales have done?

**Comment by divinenickname** [comment]
@bodiam hi, thanks for suggestion. I need a little bit time and I’ll add female names too

**Comment by bodiam** [comment]
Hi @divinenickname , we're planning on releasing 1.4.0 soon. Any chance to include this PR in the release?

**Comment by divinenickname** [comment]
@bodiam sorry for waiting, i'll finish today my pr
Thanks

**Comment by bodiam** [comment]
@divinenickname no rush at all, we can always add it to a next version of Datafaker if that's more convenient!

**Comment by divinenickname** [comment]
@bodiam ready for review, thanks

**Comment by bodiam** [comment]
Thanks! What's the source you used for these names?

**Comment by divinenickname** [comment]
@bodiam it's from one of my philippines projects. I took last 20 verified first + last names

**Comment by bodiam** [comment]
@divinenickname thanks for the PR, great start to have some Philippino content!

**Pull request merged**
