### PR TITLE
Add ISO 4217 numeric currency code faker in Currency faker group

### PR DESCRIPTION
**Pull request by panilya**
Source: https://en.wikipedia.org/wiki/ISO_4217#Active_codes_(list_one)

### CODE REVIEW

**Comment by bodiam** [comment]
Nice! Thanks @panilya !

**Comment by kingthorin** [comment]
Before the next actually release you're going to need to do a find/replace in the code base to ensure things say the proper @since version (2.1.1 or 2.2.0)

**Comment by bodiam** [comment]
@kingthorin yeah, I saw that, that's fine. I'll probably remove all 2.1.1 references, and call it 2.2.0.

**Comment by kingthorin** [comment]
Great, just wanted to make sure it was on the radar 😁

**Comment by bodiam** [comment]
@kingthorin it is. Doesn't mean I won't forget it though. I'll make a task for this!

**Comment by bodiam** [comment]
@kingthorin https://github.com/datafaker-net/datafaker/issues/1113

**Pull request merged**
