### PR TITLE
Added Ticker datasets for NSE and LSE exchanges

### PR DESCRIPTION
**Pull request by ChiragMangukia**
Added Scrips from the National Stock Exchange (NSE) India and the London Stock Exchange

### CODE REVIEW

**Comment by bodiam** [comment]
Seems these files are getting a bit big. Your contribution is most welcome though, I'll merge it in! Thanks!

**Comment by ChiragMangukia** [comment]
Thank you @bodiam! I have a question. I noticed that we have Nasdaq and NYSE tickers in the Finance provider as well. Is it intentional to keep them in both providers?

**Comment by bodiam** [comment]
@ChiragMangukia hips point. Probably not, and it might be good to deprecate the one in Finance. We usually don't introduce breaking changes without a warning depreciation first, but there's generally not a great reason to have the same list in 2 places.

**Comment by ChiragMangukia** [comment]
Noted!

Addressed it in an another PR #1129

Thank you!

**Pull request merged**
