### PR TITLE
Support japan passport number

### PR DESCRIPTION
**Pull request by yuokada**
issue: #268

### CODE REVIEW

**Comment by yuokada** [comment]
@snuyanzin or @bodiam Could you please take a look if you have a chance?

**Comment by bodiam** [comment]
@yuokada Thanks for the PR, looks fine to me! It will be available in the 1.6.0-SNAPSHOT in a few minutes.

**Comment by yuokada** [comment]
@bodiam Thanks for reviewing and merging my PR. 😄

**Comment by epragtbeamtree** [comment]
@yuokada My pleasure, you contribution is welcome!

**Pull request merged**
