### PR TITLE
[refactoring] simplify COWMap

### PR DESCRIPTION
**Pull request by asolntsev**
I have no idea what "COW" means, but it seems we just need an old good synchronized map (provided by Java SDK).

In future, we could even replace all usages of COWMap by `synchronizedMap`.

### CODE REVIEW

**Comment by kingthorin** [comment]
I believe COW == CopyOnWrite

**Review by snuyanzin — CHANGES_REQUESTED** [review]
Thanks for looking into that
IIRC the idea here was that these maps are filled only once per provider in case the provider is in use. After that the provider related info is only read from those maps. For that reason copy on write is used here.

The problem with synchronized map is that they make things drastically slower

I made some basic measurements with help of https://github.com/datafaker-net/datafaker-benchmark
like
```
mvn clean package exec:exec -Dbenchmarks="DatafakerSimpleMethods" -Ddatafaker.version=2.2.3-SNAPSHOT
```

before this PR
```
Benchmark                              Mode  Cnt      Score     Error   Units
DatafakerSimpleMethods.firstname      thrpt   10   4782.533 ±  20.500  ops/ms
DatafakerSimpleMethods.fullname       thrpt   10   1697.407 ±  25.530  ops/ms
DatafakerSimpleMethods.numberBetween  thrpt   10  45964.335 ± 237.500  ops/ms
DatafakerSimpleMethods.streetAddress  thrpt   10   1246.463 ±  21.650  ops/ms
```

After
```
Benchmark                              Mode  Cnt      Score     Error   Units
DatafakerSimpleMethods.firstname      thrpt   10   3465.447 ±  78.319  ops/ms
DatafakerSimpleMethods.fullname       thrpt   10   1270.090 ±  38.539  ops/ms
DatafakerSimpleMethods.numberBetween  thrpt   10  45742.122 ± 624.010  ops/ms
DatafakerSimpleMethods.streetAddress  thrpt   10    974.074 ±  49.535  ops/ms
```

and it looks like it starts being up to 30% slower...

**Comment by asolntsev** [comment]
@snuyanzin Wow, interesting... Thank you for sharing the information.
Well, probably this information could be added to COWMap javadoc?

**Comment by bodiam** [comment]
@asolntsev yes, and probably renaming that class to CopyOnWriteMap wouldn't hurt either, you're not the first one to ask that it is.

**Comment by snuyanzin** [comment]
> Well, probably this information could be added to COWMap javadoc?
> and probably renaming that class to CopyOnWriteMap wouldn't hurt either, you're not the first one to ask that it is.

yes, that probably makes sense, done  at https://github.com/datafaker-net/datafaker/pull/1207

**Comment by asolntsev** [comment]
@bodiam No problems. In fact, we should rather delete this PR because it was replaced by https://github.com/datafaker-net/datafaker/pull/1207

**Pull request closed without merging**
