### PR TITLE
Add markdown documentation for unique faker

### PR DESCRIPTION
**Pull request by giunto**
This PR will add documentation for the unique faker in the main README.md as well as a separate markdown file detailing its usage. Let me know if everything written sounds okay.

### CODE REVIEW

**Comment by epragtbeamtree** [comment]
@snuyanzin Seems we still have concurrency issues.

**Comment by epragtbeamtree** [comment]
Great work @giunto , thanks. Would it be possible to add this page also to the `mkdocs.yml` file, so it's part of the index/navigation?

**Comment by giunto** [comment]
Added. Thanks for letting me know.

**Comment by bodiam** [comment]
Thanks! 

> Added. Thanks for letting me know.

No worries at all. Thanks for providing the documentation, it's live now: https://www.datafaker.net/documentation/unique-values/

**Pull request merged**
