### PR TITLE
Adding support for Tamil language

### LINKED ISSUE #1377: Add support for tamil language
We like to use this library with Tamil language.

Our application needs Tamil language fakes, so it will be better if we add the Tamil language support.

### PR DESCRIPTION
**Pull request by sann3**
PR to fix #1377

### CODE REVIEW

**Review by asolntsev — CHANGES_REQUESTED** [review]
@sann3 Thank you for the PR. Generally looks good, but I would ask for few improvements.

1. Typo in commit message: "Create confiog for Tamil language"
2. "ta" is a language used in multiple countries. While "+91" is India country code. 
So the "phone" section should be in file `src/main/resources/_IN.yml`. Phone is related to country, not language.

**Comment by kingthorin** [comment]
`05:50:20.864 [ERROR]   LocalityTest.allSupportedLocales:35 [Somebody forgot to add the new locale to Locality.LOCALES] `

**Comment by sann3** [comment]
Updated the PR with recommended changes, pls check.

**Comment by kingthorin** [comment]
@asolntsev 

>     2. "ta" is a language used in multiple countries. While "+91" is India country code.
>        So the "phone" section should be in file `src/main/resources/_IN.yml`. Phone is related to country, not language.

Same for address?

**Comment by asolntsev** [comment]
> address

Not exactly. 
For example, two-letter state codes should be in country gile, but state name, city names etc. should be in the language file because they sound differently in different languages.

**Review by asolntsev — APPROVED** [review]

**Comment by asolntsev** [comment]
@sann3 Please execute `mvn test`, and you will see some failing tests
> mvn test
>  FakerIntegrationTest.testAllFakerMethodsThatReturnStrings:100->testAllMethodsThatReturnStringsActuallyReturnStrings:122 Runtime Test for method public java.lang.String net.datafaker.providers.base.Name.fullName() and object Name(Faker@955ae44)@481a64f2 was failed for locale ta [thread: FakerIntegrationTest.testAllFakerMethodsThatReturnStrings#20438#]

The reason is that this variable is not defined in `ta.yml`:
```yml
         - "#{female_last_name}"
```

**Comment by bodiam** [comment]
Hi @sann3 , looks great, thanks. Few things:

- The file needs to be called `ta-IN.yml`. 
- In the file, please change the `name:` field to this:

```
      name:
        - "#{male_first_name}"
        - "#{female_first_name}"
```

When both items have been done, we can merge the PR!

**Comment by sann3** [comment]
FakerIntegrationTest.testAllFakerMethodsThatReturnStrings test is failing with " Error type: NOT_A_NUMBER. The string supplied did not seem to be a phone number."

If I rename to ta-IN.yml, all the tests are passing. What should I do ?

**Comment by asolntsev** [comment]
@sann3 All good, I've merged your PR and made few changes in a new PR https://github.com/datafaker-net/datafaker/pull/1385/commits

That was not trivial because of some legacy and hacks in DF code. :)

**Comment by sann3** [comment]
Can someone pleas add hacktoberfest-accepted label for this pr

**Comment by asolntsev** [comment]
Em... why? This PR is already merged.

**Comment by sann3** [comment]
So that it will be counted against the my hacktoberfest Pr count.

**Comment by sann3** [comment]
Thank you

**Pull request merged**
